source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'jekyll'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-github-metadata'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-twitter-plugin'
    gem 'jekyll-sitemap'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
    gem 'jekyll-seo-tag'
    gem 'wdm', '>= 0.1.0'
    gem 'eventmachine', '1.2.7', git: 'https://github.com/eventmachine/eventmachine.git', tag: 'v1.2.7'
end
